import docker
import asyncio
import os
import re
import secrets
import shutil
from typing import Optional, Dict, Any
from docker.errors import APIError, NotFound

from config.settings import Settings


def voice_port_for(mc_port: int) -> int:
    """mc port 와 같은 offset 의 voicechat UDP port. 한 호스트에 여러 voicechat 동시 운영 가능."""
    return Settings.VOICE_PORT_BASE + (mc_port - Settings.PORT_START)


def write_voicechat_config(name: str, loader: str, voice_port: int) -> None:
    """voicechat-server.properties 를 컨테이너 첫 부팅 전에 미리 생성.

    voicechat 은 properties 가 이미 있으면 그 값을 읽고, missing key 는 default 로 채운다.
    voice_host 를 빈 문자열로 두면 클라이언트가 hostname 자동 추정하다 잘못된 곳으로 가서
    'Disconnecting client' 가 나는 경우가 많으므로 PUBLIC_HOST:voice_port 로 명시한다.
    VANILLA 는 voicechat 자체가 없어 매핑이 없으니 스킵.
    """
    rel = Settings.VOICECHAT_CONFIG_PATH.get(loader)
    if rel is None:
        return
    path = f"/docker/minecraft/{name}/{rel}"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(
            "# Auto-generated by minecraft-discord-bot — do not edit `port` / `voice_host` by hand.\n"
            f"port={voice_port}\n"
            "bind_address=0.0.0.0\n"
            f"voice_host={Settings.PUBLIC_HOST}:{voice_port}\n"
        )


_MINERTRACK_CONFIG_YAML = """\
# Auto-generated by minecraft-discord-bot — do not edit `xray.commands` by hand.
# 기본 config + VL 7 자동 ban 추가. 다른 키는 MinerTrack 기본값 유지.
_config-version: 2

check_update: true
check_update_channel: "stable"

kick_strike_lightning: true

log_file: true

delete_time: 30

disable_bypass_permission: false

DiscordWebHook:
  enable: false
  WebHookURL: ''
  vl-required: 4

xray:
  worlds:
    'overworld':
      - world
      - all_unnamed_world
    'nether':
      - world_nether
    'end':
      - world_the_end

  decay:
    interval: 3
    amount: 1
    use_factor: false
    factor: 0.9

  commands:
    2: 'minertrack notify &f%player% &7triggered &fX-Ray &7detection [&cVL: 2&7]'
    4: 'minertrack notify &f%player% &7triggered &fX-Ray &7detection [&cVL: 4&7]'
    5:
      - 'minertrack kick %player% X-Ray'
      - 'minertrack notify &f%player% &7was kicked for &fX-Ray'
    7:
      - 'ban %player% [X-Ray] auto-detected by MinerTrack'
      - 'minertrack notify &f%player% &7was &cbanned&7 for &fX-Ray'
"""


def write_minertrack_config(name: str, loader: str) -> None:
    """MinerTrack config.yml 을 컨테이너 첫 부팅 전에 써둘.

    MinerTrack 은 Paper API 의존 — PAPER 외 로더는 jar 자체가 안 깔려서 무의미.
    기본 정책은 VL 5 = kick (MinerTrack 기본), VL 7 = 영구 ban (우리 추가).
    이 파일이 없으면 플러그인이 첫 부팅 시 기본 config 를 쓰는데, 그 기본엔 ban 명령이 없다.
    """
    if (loader or "").upper() != "PAPER":
        return
    path = f"/docker/minecraft/{name}/{Settings.MINERTRACK_CONFIG_PATH}"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(_MINERTRACK_CONFIG_YAML)


def select_image(mod_loader: str, version: str) -> str:
    """모드 로더/버전에 맞는 itzg 이미지 태그를 결정합니다.

    - 1.x 시리즈의 SPIGOT/BUKKIT: BuildTools 가 신 Java 를 거부 → java21
    - 1.20.x 이하 모든 로더: 안전하게 java21
    - 26.x 시리즈 (mc 신 버전 체계): jar 자체가 Java 25 컴파일 → :latest
      * SPIGOT 26.1.x 도 jar 가 Java 25 (class version 69.0) 라 :latest 필요.
        이전 SPIGOT 옥 정책(무조건 :java21) 으로 보내면 UnsupportedClassVersionError 발생.
    - 그 외(LATEST, 1.21+): 기본 이미지 (Java 25)
    """
    loader = (mod_loader or "VANILLA").upper()
    ver = (version or "LATEST").upper()

    legacy_match = re.match(r"^1\.(\d+)", ver)
    is_legacy_1x = bool(legacy_match)

    # 1.x 시리즈의 SPIGOT/BUKKIT: BuildTools 가 java25 거부
    if loader in Settings.JAVA21_REQUIRED_LOADERS and is_legacy_1x:
        return Settings.MINECRAFT_IMAGE_JAVA21

    # 1.20.x 이하: 모든 로더가 java21 안전
    if is_legacy_1x and int(legacy_match.group(1)) <= 20:
        return Settings.MINECRAFT_IMAGE_JAVA21

    return Settings.MINECRAFT_IMAGE


class DockerService:
    """Wrapper for Docker SDK operations with security hardening."""

    def __init__(self):
        self.client = docker.DockerClient(base_url='unix:///var/run/docker.sock')
        self._ensure_network()

    def _ensure_network(self):
        """Ensure the minecraft network exists."""
        try:
            self.client.networks.get("minecraft-network")
        except NotFound:
            self.client.networks.create(
                name="minecraft-network",
                driver="bridge",
                internal=False
            )

    def _purge_volume_dir(self, name: str) -> None:
        """이전 서버 데이터(host bind dir) 가 남아 있으면 강제 삭제.

        같은 이름으로 다시 만들었을 때 옥 level.dat 이 그대로 마운트돼
        "같은 맵이 다시 나온다" 는 현상을 막기 위함. shutil.rmtree 로 먼저 시도,
        root-소유 파일 권한 문제로 실패하면 alpine 컨테이너로 폴백 정리.
        """
        path = f"/docker/minecraft/{name}"
        if not os.path.isdir(path):
            return
        shutil.rmtree(path, ignore_errors=True)
        if not os.path.isdir(path):
            return
        # rmtree 실패 — 컨테이너가 root 로 만든 파일이 남았을 가능성. alpine 으로 강제 정리.
        try:
            self.client.containers.run(
                "alpine",
                command=["sh", "-c", f"rm -rf /data/{name}"],
                volumes={"/docker/minecraft": {"bind": "/data", "mode": "rw"}},
                remove=True,
            )
        except Exception:
            # 마지막 폴백 실패해도 itzg 가 dir 안 비어 있으면 그 위에 새 월드를 만들지 않으므로
            # 여기서 raise 하지 않고 호출부가 컨테이너 생성에서 결국 실패하도록 둔.
            pass

    async def create_container(
        self,
        name: str,
        port: int,
        ram_mb: Optional[int] = None,
        cpu: float = 1.0,
        mod_loader: str = "VANILLA",
        version: Optional[str] = None,     # None → Settings.DEFAULT_VERSION
        enable_anti_xray: bool = True,
        # itzg/minecraft-server 환경변수로 직결되는 옵션들. None 이면 itzg 기본값.
        difficulty: Optional[str] = None,
        gamemode: Optional[str] = None,
        max_players: Optional[int] = None,
        motd: Optional[str] = None,
        pvp: Optional[bool] = None,
        level_type: Optional[str] = None,
        seed: Optional[str] = None,
        hardcore: Optional[bool] = None,
        allow_nether: Optional[bool] = None,
        view_distance: Optional[int] = None,
        spawn_protection: Optional[int] = None,
        online_mode: Optional[bool] = None,
        ram_gb: Optional[int] = None,       # 명시 시 자동 RAM 정책 override
        whitelist: Optional[bool] = None,
    ) -> Dict[str, Any]:
        """Create a Minecraft server container with security limits."""
        volume_path = f"/docker/minecraft/{name}"
        mods_path = f"/docker/minecraft/{name}/mods"

        # 같은 이름으로 다시 만드는 경우 옥 월드 데이터가 마운트돼 같은 맵이 떠오르는 사고 방지.
        # 이 시점에 같은 이름 컨테이너는 이미 존재하지 않음(server_service 가 사전 검증).
        self._purge_volume_dir(name)

        loader = (mod_loader or "VANILLA").upper()
        ver = (version or Settings.DEFAULT_VERSION).strip() or Settings.DEFAULT_VERSION
        # 사용자가 'lastest' 같은 흔한 오타를 보내도 정상 동작하도록
        if ver.lower() in {"lastest", "latst", "lates"}:
            ver = "LATEST"

        # 자동 RAM: SPIGOT/BUKKIT 은 BuildTools + 월드 생성 비용이 커서 OOM 위험 → 4GB.
        # 사용자가 ram_gb 를 명시하면 그 값 우선 (Settings.MAX_RAM_MB 상한).
        if ram_gb is not None:
            ram_mb = max(1, min(ram_gb, Settings.MAX_RAM_MB // 1024)) * 1024
        elif ram_mb is None:
            ram_mb = 4096 if loader in Settings.JAVA21_REQUIRED_LOADERS else 2048

        # seed: 사용자 지정 우선, 미지정이면 매번 새 랜덤 시드(Java long 양수 범위).
        # 미지정 시 itzg 가 빈 SEED 를 무시하므로 MC 가 자체 랜덤 시드를 쓰긴 하지만,
        # 호환성·재현성을 위해 봇이 시드를 명시적으로 결정하고 결과에 담아 반환한다.
        effective_seed = (seed or "").strip() or str(secrets.randbits(63))

        environment = {
            "EULA": "TRUE",
            "MEMORY": f"{ram_mb // 1024}G",
            "UID": "0",
            "GID": "0",
            "TYPE": loader,
            "VERSION": ver,
            "SEED": effective_seed,
            # RCON — /sayall, /tps 등 봇 명령 처리에 필요. 외부 포트는 노출하지 않음 (network 내부 접근만).
            "ENABLE_RCON": "TRUE",
            "RCON_PASSWORD": Settings.RCON_PASSWORD,
            "RCON_PORT": str(Settings.RCON_PORT),
        }

        # itzg env 매핑 (None 이면 키 자체를 안 넣어 itzg 기본값에 맡김).
        def _bool(v: bool) -> str:
            return "TRUE" if v else "FALSE"

        if difficulty:
            environment["DIFFICULTY"] = difficulty
        if gamemode:
            environment["MODE"] = gamemode
        if max_players is not None:
            environment["MAX_PLAYERS"] = str(max_players)
        if motd:
            environment["MOTD"] = motd
        if pvp is not None:
            environment["PVP"] = _bool(pvp)
        if level_type:
            environment["LEVEL_TYPE"] = level_type
        if hardcore is not None:
            environment["HARDCORE"] = _bool(hardcore)
        if allow_nether is not None:
            environment["ALLOW_NETHER"] = _bool(allow_nether)
        if view_distance is not None:
            environment["VIEW_DISTANCE"] = str(view_distance)
        if spawn_protection is not None:
            environment["SPAWN_PROTECTION"] = str(spawn_protection)
        if online_mode is not None:
            environment["ONLINE_MODE"] = _bool(online_mode)
        if whitelist is not None:
            environment["WHITE_LIST"] = _bool(whitelist)

        # Modrinth / SpigetMC 자동 설치 목록 빌드.
        # VANILLA 는 모드/플러그인 시스템이 없으므로 자동 설치 전체 스킵.
        modrinth_projects: list[str] = []
        spiget_resources: list[str] = []
        anti_xray_project = None
        if loader != "VANILLA":
            if enable_anti_xray:
                anti_xray_project = Settings.ANTI_XRAY_PROJECTS.get(loader)
                if anti_xray_project:
                    modrinth_projects.extend(anti_xray_project.split(","))
                spiget_dep = Settings.ANTI_XRAY_SPIGET_DEPS.get(loader)
                if spiget_dep:
                    spiget_resources.append(spiget_dep)
            # 모든 로더 공통 (paper/fabric 양쪽 jar 가 modrinth 에 있는 것만)
            modrinth_projects.extend(Settings.ALWAYS_INSTALL_MODRINTH)
            # 모드 로더 jar 만 modrinth 에 있는 것 (예: spark)
            modrinth_projects.extend(Settings.ALWAYS_INSTALL_MODRINTH_BY_LOADER.get(loader, []))
            # Bukkit 계열 SpigetMC 자동 설치 (예: paper 용 spark = 57242)
            spiget_resources.extend(Settings.ALWAYS_INSTALL_SPIGET_BY_LOADER.get(loader, []))

        if modrinth_projects:
            seen = set()
            uniq = [p for p in modrinth_projects if not (p in seen or seen.add(p))]
            environment["MODRINTH_PROJECTS"] = ",".join(uniq)
            environment["MODRINTH_DOWNLOAD_DEPENDENCIES"] = "required"

        if spiget_resources:
            seen = set()
            uniq = [r for r in spiget_resources if not (r in seen or seen.add(r))]
            environment["SPIGET_RESOURCES"] = ",".join(uniq)

        image = select_image(loader, ver)

        # voicechat 동적 포트 — mc port 와 같은 offset.
        # VANILLA 는 voicechat 설치 자체가 안 되니 properties 만 안 쓰면 됨 (publish 는 해도 무해).
        voice_port = voice_port_for(port)
        write_voicechat_config(name, loader, voice_port)
        # MinerTrack(자동 ban) 설정 — PAPER 만 써짐, 그 외 로더는 no-op.
        write_minertrack_config(name, loader)

        # Security-hardened container configuration
        container = self.client.containers.create(
            image=image,
            name=name,
            environment=environment,
            volumes={
                volume_path: {"bind": "/data", "mode": "rw"},
                mods_path: {"bind": "/mods", "mode": "rw"},
            },
            # 25565/tcp = MC 게임 포트, 24454/udp = simple-voice-chat 음성 포트.
            # voicechat 의 listen port 를 voice_port 로 강제(properties)했으므로
            # host:voice_port/UDP → container:voice_port/UDP 로 1:1 매핑.
            ports={"25565/tcp": port, f"{voice_port}/udp": voice_port},
            network="minecraft-network",
            dns=["8.8.8.8", "1.1.1.1"],   # 호스트 DNS 장애 시에도 모드/플러그인 다운로드 가능
            # 자원 제한 없음 — 호스트 가용 CPU/메모리 모두 사용해서 부팅·플러그인 로드 빠르게.
            # 자바 heap 은 환경변수 MEMORY 로 통제 (SPIGOT 4G, 그 외 2G — itzg 가 -Xmx 설정).
            # 한 호스트에 컨테이너 여러 대 띄울 때는 OOM 위험 사용자 책임.
            restart_policy={"Name": "on-failure", "MaximumRetryCount": 3},
            cap_drop=["NET_ADMIN", "SYS_ADMIN"], 
	    cap_add=["CHOWN", "SETUID", "SETGID"],
            security_opt=["no-new-privileges:true"],
            detach=True
        )

        return {
            "id": container.id,
            "name": container.name,
            "port": port,
            "voice_port": voice_port if loader != "VANILLA" else None,
            "mod_loader": loader,
            "version": ver,
            "image": image,
            "mods_path": mods_path,
            "anti_xray": anti_xray_project,  # 적용된 Modrinth slug, 또는 None
            "seed": effective_seed,
        }

    async def start_container(self, name: str) -> bool:
        """Start a container by name."""
        try:
            container = self.client.containers.get(name)
            container.start()
            return True
        except NotFound:
            return False

    async def stop_container(self, name: str) -> bool:
        """Stop a container by name."""
        try:
            container = self.client.containers.get(name)
            container.stop(timeout=30)
            return True
        except NotFound:
            return False

    async def delete_container(self, name: str) -> bool:
        """Delete a container AND its bind-mounted data directory.

        Why: 봇은 named volume 이 아니라 host bind mount (/docker/minecraft/<name>) 를 쓴다.
        컨테이너만 지우고 디렉토리를 두면 같은 이름으로 다시 /create 해도 옥 월드/플러그인이
        그대로 마운트돼서 사용자가 "삭제했는데 같은 맵이 나온다" 는 혼란을 격는다.
        """
        try:
            container = self.client.containers.get(name)
            container.remove(force=True)
        except NotFound:
            return False

        # bind mount 디렉토리 정리. 봇이 root 로 돌아 root-소유 파일도 지움.
        volume_path = f"/docker/minecraft/{name}"
        if os.path.isdir(volume_path):
            shutil.rmtree(volume_path, ignore_errors=True)

        return True

    async def list_containers(self) -> list[Dict[str, Any]]:
        """itzg/minecraft-server 이미지 컨테이너만 마인크래프트 서버로 취급."""
        containers = []
        for container in self.client.containers.list(all=True):
            tags = container.image.tags or []
            if not any("itzg/minecraft-server" in t.lower() for t in tags):
                continue

            ports = container.attrs.get('NetworkSettings', {}).get('Ports', {})
            host_port = None
            if '25565/tcp' in ports and ports['25565/tcp']:
                host_port = int(ports['25565/tcp'][0]['HostPort'])

            containers.append({
                "name": container.name,
                "status": container.status,
                "id": container.id[:12],
                "port": host_port,
            })
        return containers

    async def get_status(self, name: str) -> Optional[Dict[str, Any]]:
        """Get detailed status of a container."""
        try:
            container = self.client.containers.get(name)
            ports = container.attrs.get('NetworkSettings', {}).get('Ports', {})
            host_port = None
            if '25565/tcp' in ports and ports['25565/tcp']:
                host_port = int(ports['25565/tcp'][0]['HostPort'])

            env_list = container.attrs.get('Config', {}).get('Env', []) or []
            env_dict = {}
            for entry in env_list:
                if "=" in entry:
                    k, v = entry.split("=", 1)
                    env_dict[k] = v

            return {
                "name": container.name,
                "status": container.status,
                "port": host_port,
                "created": container.attrs['Created'],
                "mod_loader": env_dict.get("TYPE", "VANILLA"),
                "version": env_dict.get("VERSION", "LATEST"),
            }
        except NotFound:
            return None
